/**
 * AI Files generators — wszystkie "well-known" pliki, których oczekują AI crawlery
 * i agenty:
 *
 *   /llms.txt                       — AnswerDotAI spec (Jeremy Howard 2024)
 *   /llms-full.txt                  — pełna treść strony, jeden plik dla agentów
 *   /robots.txt                     — z poprawnym split GPTBot vs OAI-SearchBot itd.
 *   /sitemap.xml                    — standardowy sitemap (jeśli brak)
 *   /feed.xml                       — RSS feed (Perplexity polluje co 1-6h)
 *   /.well-known/agent-card.json    — A2A spec (Google) — discovery dla agentów
 *   /.well-known/mcp.json           — manifest naszego MCP-over-HTTP endpointu
 *   /_headers                       — Cloudflare/Netlify Content-Signal headers
 *   /skill.md                       — Osmani Agentic Engine Optimization layer 3
 *   /AGENTS.md                      — emerging standard (20k+ repos, OpenAI/Cursor)
 *
 * Wszystkie generatory są pure functions: input → string. Adaptery decydują
 * gdzie to zapisać (filesystem, response handler, build-time output).
 */

import type { SiteToMcpConfig } from '../../types/index.js';

// ============================================================================
// llms.txt — AnswerDotAI spec
// ============================================================================

export interface LlmsTxtSection {
  title: string;
  links: Array<{
    url: string;
    title: string;
    description?: string;
  }>;
}

export interface LlmsTxtInput {
  siteName: string;
  siteDescription?: string;
  siteUrl: string;
  /** Krótkie podsumowanie strony (1-3 zdania) — pojawia się jako quote-block */
  blockquote?: string;
  sections: LlmsTxtSection[];
  /** Sekcja Optional zawiera pages mniej krytyczne — agent może je pominąć */
  optional?: LlmsTxtSection;
}

export function generateLlmsTxt(input: LlmsTxtInput): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${input.siteName}`);
  lines.push('');

  if (input.siteDescription) {
    lines.push(`> ${input.siteDescription}`);
    lines.push('');
  } else if (input.blockquote) {
    lines.push(`> ${input.blockquote}`);
    lines.push('');
  }

  // Sections
  for (const section of input.sections) {
    lines.push(`## ${section.title}`);
    lines.push('');
    for (const link of section.links) {
      const desc = link.description ? `: ${link.description}` : '';
      lines.push(`- [${link.title}](${link.url})${desc}`);
    }
    lines.push('');
  }

  // Optional
  if (input.optional) {
    lines.push(`## Optional`);
    lines.push('');
    for (const link of input.optional.links) {
      const desc = link.description ? `: ${link.description}` : '';
      lines.push(`- [${link.title}](${link.url})${desc}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ============================================================================
// llms-full.txt — pełna treść strony
// ============================================================================

export interface LlmsFullInput {
  siteName: string;
  pages: Array<{
    url: string;
    title: string;
    markdown: string;
    /** Token count (approx, do flagowania >30k limit) */
    tokens?: number;
  }>;
  /** Cap całego pliku w tokenach (Osmani: agenci truncują >30k cicho) */
  maxTokens?: number;
}

export function generateLlmsFullTxt(input: LlmsFullInput): { content: string; truncated: boolean; totalTokens: number } {
  const lines: string[] = [];
  lines.push(`# ${input.siteName}`);
  lines.push('');
  lines.push(`> Pełna treść strony przeznaczona dla AI agentów. Generated by @vidok/site-to-mcp.`);
  lines.push('');

  let totalTokens = 0;
  let truncated = false;
  const cap = input.maxTokens ?? 28000; // bezpieczny default poniżej 30k

  for (const page of input.pages) {
    const tokens = page.tokens ?? Math.ceil(page.markdown.length / 4);
    if (totalTokens + tokens > cap) {
      lines.push(`---`);
      lines.push(`<!-- Truncated: reached ${cap} token cap. Remaining pages omitted. -->`);
      truncated = true;
      break;
    }
    lines.push(`---`);
    lines.push('');
    lines.push(`# ${page.title}`);
    lines.push(`Source: ${page.url}`);
    lines.push('');
    lines.push(page.markdown.trim());
    lines.push('');
    totalTokens += tokens;
  }

  return { content: lines.join('\n'), truncated, totalTokens };
}

// ============================================================================
// robots.txt — z 6 AI bots split (research May 2026)
// ============================================================================

export interface RobotsTxtInput {
  siteUrl: string;
  /** Allow/disallow per bot. Split na search vs training bots. */
  aiBots: SiteToMcpConfig['aiBots'];
  /** Ścieżka sitemap (default /sitemap.xml) */
  sitemapPath?: string;
  /** Custom disallow paths (np. /admin, /private) */
  disallow?: string[];
  /** Domyślny disallow dla wszystkich (User-agent: *) */
  defaultDisallow?: string[];
}

/**
 * Splits AI bots into "search/citation" (allow by default — to są bots które
 * dają cytowania) vs "training" (decyzja użytkownika).
 *
 * Source: nohacks.co/blog/ai-user-agents-landscape-2026
 */
const AI_BOT_GROUPS = {
  search: ['OAI-SearchBot', 'ChatGPT-User', 'PerplexityBot', 'Claude-SearchBot', 'Claude-User', 'Bingbot'],
  training: ['GPTBot', 'ClaudeBot', 'Google-Extended', 'AppleBot-Extended', 'CCBot', 'YouBot', 'Bytespider', 'Meta-ExternalAgent'],
  ambiguous: ['Applebot', 'FacebookExternalHit'],
};

export function generateRobotsTxt(input: RobotsTxtInput): string {
  const lines: string[] = [];
  const sitemapPath = input.sitemapPath ?? '/sitemap.xml';

  lines.push('# robots.txt — generated by @vidok/site-to-mcp');
  lines.push(`# Last updated: ${new Date().toISOString().slice(0, 10)}`);
  lines.push('');

  // User-agent: * (default)
  lines.push('User-agent: *');
  if (input.defaultDisallow && input.defaultDisallow.length > 0) {
    for (const path of input.defaultDisallow) lines.push(`Disallow: ${path}`);
  } else {
    lines.push('Allow: /');
  }
  lines.push('');

  // Per AI bot
  const allBots = Object.keys(input.aiBots) as Array<keyof typeof input.aiBots>;
  for (const bot of allBots) {
    const allowed = input.aiBots[bot];
    lines.push(`# ${bot} — ${getBotPurpose(bot)}`);
    lines.push(`User-agent: ${bot}`);
    if (allowed) {
      lines.push('Allow: /');
      if (input.disallow) for (const d of input.disallow) lines.push(`Disallow: ${d}`);
    } else {
      lines.push('Disallow: /');
    }
    lines.push('');
  }

  // Sitemap
  lines.push(`Sitemap: ${input.siteUrl.replace(/\/$/, '')}${sitemapPath}`);

  return lines.join('\n');
}

function getBotPurpose(bot: string): string {
  if (AI_BOT_GROUPS.search.includes(bot)) return 'search/citations (recommended: allow)';
  if (AI_BOT_GROUPS.training.includes(bot)) return 'training (your choice)';
  return 'mixed purpose';
}

// ============================================================================
// sitemap.xml
// ============================================================================

export interface SitemapEntry {
  loc: string;
  lastmod?: string; // ISO date
  changefreq?: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority?: number; // 0.0 - 1.0
  /** Hreflang alternates */
  alternates?: Array<{ lang: string; href: string }>;
}

export function generateSitemapXml(entries: SitemapEntry[]): string {
  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"');
  lines.push('        xmlns:xhtml="http://www.w3.org/1999/xhtml">');

  for (const e of entries) {
    lines.push('  <url>');
    lines.push(`    <loc>${escapeXml(e.loc)}</loc>`);
    if (e.lastmod) lines.push(`    <lastmod>${e.lastmod}</lastmod>`);
    if (e.changefreq) lines.push(`    <changefreq>${e.changefreq}</changefreq>`);
    if (typeof e.priority === 'number') lines.push(`    <priority>${e.priority.toFixed(1)}</priority>`);
    if (e.alternates) {
      for (const alt of e.alternates) {
        lines.push(`    <xhtml:link rel="alternate" hreflang="${alt.lang}" href="${escapeXml(alt.href)}"/>`);
      }
    }
    lines.push('  </url>');
  }

  lines.push('</urlset>');
  return lines.join('\n');
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// ============================================================================
// RSS feed (Perplexity polluje co 1-6h vs days dla recrawl)
// ============================================================================

export interface RssItem {
  title: string;
  link: string;
  description: string;
  pubDate: string; // RFC 822 lub ISO (sconvert)
  author?: string;
  categories?: string[];
  guid?: string;
}

export interface RssFeedInput {
  title: string;
  link: string;
  description: string;
  language?: string;
  copyright?: string;
  items: RssItem[];
  selfLink?: string; // self-reference (atom:link)
}

export function generateRss(input: RssFeedInput): string {
  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">');
  lines.push('  <channel>');
  lines.push(`    <title>${escapeXml(input.title)}</title>`);
  lines.push(`    <link>${escapeXml(input.link)}</link>`);
  lines.push(`    <description>${escapeXml(input.description)}</description>`);
  if (input.language) lines.push(`    <language>${input.language}</language>`);
  if (input.copyright) lines.push(`    <copyright>${escapeXml(input.copyright)}</copyright>`);
  if (input.selfLink) {
    lines.push(`    <atom:link href="${escapeXml(input.selfLink)}" rel="self" type="application/rss+xml" />`);
  }
  lines.push(`    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>`);

  for (const item of input.items) {
    const pubDate = item.pubDate.includes('T') ? new Date(item.pubDate).toUTCString() : item.pubDate;
    // CDATA injection guard: jeśli description ma `]]>`, breakout zamykania.
    const safeDesc = item.description.replace(/]]>/g, ']]]]><![CDATA[>');
    lines.push('    <item>');
    lines.push(`      <title>${escapeXml(item.title)}</title>`);
    lines.push(`      <link>${escapeXml(item.link)}</link>`);
    lines.push(`      <description><![CDATA[${safeDesc}]]></description>`);
    lines.push(`      <pubDate>${pubDate}</pubDate>`);
    if (item.author) lines.push(`      <author>${escapeXml(item.author)}</author>`);
    if (item.categories) {
      for (const c of item.categories) lines.push(`      <category>${escapeXml(c)}</category>`);
    }
    lines.push(`      <guid isPermaLink="true">${escapeXml(item.guid ?? item.link)}</guid>`);
    lines.push('    </item>');
  }

  lines.push('  </channel>');
  lines.push('</rss>');
  return lines.join('\n');
}

// ============================================================================
// /.well-known/agent-card.json (A2A spec, Google) — discovery dla agentów
// ============================================================================

export interface AgentCardInput {
  name: string;
  description: string;
  siteUrl: string;
  /** Lista capabilities — co agent może zrobić na tej stronie */
  capabilities?: string[];
  /** Lista endpointów (MCP, REST API) */
  endpoints?: {
    mcp?: string; // np. /.well-known/mcp.json
    rest?: string; // np. /api/llm/v1
    llmsTxt?: string;
  };
  contact?: { email?: string };
}

export function generateAgentCard(input: AgentCardInput): string {
  const card: Record<string, unknown> = {
    schemaVersion: 'a2a/2026-01',
    name: input.name,
    description: input.description,
    url: input.siteUrl,
  };
  if (input.capabilities) card['capabilities'] = input.capabilities;
  if (input.endpoints) card['endpoints'] = input.endpoints;
  if (input.contact) card['contact'] = input.contact;
  return JSON.stringify(card, null, 2);
}

// ============================================================================
// _headers (Cloudflare/Netlify) — Content-Signal pattern z agentmarkup
// ============================================================================

export interface HeadersFileInput {
  /** Per-path headers */
  paths: Array<{
    pattern: string; // np. "/*", "/blog/*"
    headers: Record<string, string>;
  }>;
  /** Globalny Content-Signal dla całej domeny */
  globalContentSignal?: {
    aiTrain: 'yes' | 'no' | 'partial';
    aiSearch: 'yes' | 'no';
    aiReasoning: 'yes' | 'no';
  };
}

export function generateHeadersFile(input: HeadersFileInput): string {
  const lines: string[] = [];

  if (input.globalContentSignal) {
    const cs = [
      `ai-train=${input.globalContentSignal.aiTrain}`,
      `ai-search=${input.globalContentSignal.aiSearch}`,
      `ai-reasoning=${input.globalContentSignal.aiReasoning}`,
    ].join(', ');
    lines.push('/*');
    lines.push(`  Content-Signal: ${cs}`);
    lines.push('');
  }

  for (const path of input.paths) {
    lines.push(path.pattern);
    for (const [k, v] of Object.entries(path.headers)) {
      lines.push(`  ${k}: ${v}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ============================================================================
// skill.md (Osmani layer 3 — Agentic Engine Optimization)
// ============================================================================

export interface SkillMdInput {
  name: string;
  description: string;
  capabilities: string[];
  /** Krok-po-kroku jak agent może użyć strony */
  howToUse: string[];
  /** Endpointy lub URL-e do skorzystania */
  endpoints?: Record<string, string>;
  examples?: Array<{ task: string; steps: string[] }>;
}

export function generateSkillMd(input: SkillMdInput): string {
  const lines: string[] = [];
  lines.push(`# ${input.name}`);
  lines.push('');
  lines.push(input.description);
  lines.push('');
  lines.push('## Capabilities');
  lines.push('');
  for (const c of input.capabilities) lines.push(`- ${c}`);
  lines.push('');

  lines.push('## How to use');
  lines.push('');
  for (let i = 0; i < input.howToUse.length; i++) {
    lines.push(`${i + 1}. ${input.howToUse[i]}`);
  }
  lines.push('');

  if (input.endpoints && Object.keys(input.endpoints).length > 0) {
    lines.push('## Endpoints');
    lines.push('');
    for (const [k, v] of Object.entries(input.endpoints)) {
      lines.push(`- **${k}**: ${v}`);
    }
    lines.push('');
  }

  if (input.examples && input.examples.length > 0) {
    lines.push('## Examples');
    lines.push('');
    for (const ex of input.examples) {
      lines.push(`### ${ex.task}`);
      lines.push('');
      for (let i = 0; i < ex.steps.length; i++) {
        lines.push(`${i + 1}. ${ex.steps[i]}`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ============================================================================
// AGENTS.md (emerging standard, 20k+ repos)
// Per ETH Zurich March 2026: human-written non-inferable details only.
// Plugin nie generuje content — tylko skeleton do wypełnienia.
// ============================================================================

export interface AgentsMdInput {
  projectName: string;
  /** Detale których agent NIE wywnioskuje z kodu */
  nonInferable: {
    architecture?: string;
    conventions?: string;
    testing?: string;
    deployment?: string;
    pitfalls?: string;
  };
}

export function generateAgentsMd(input: AgentsMdInput): string {
  const lines: string[] = [];
  lines.push(`# ${input.projectName} — Agent Context`);
  lines.push('');
  lines.push('> This file documents non-inferable project details for AI agents.');
  lines.push('> Following ETH Zurich (March 2026) guidance: human-written details only.');
  lines.push('');

  const sections: Array<[string, string | undefined]> = [
    ['Architecture', input.nonInferable.architecture],
    ['Conventions', input.nonInferable.conventions],
    ['Testing', input.nonInferable.testing],
    ['Deployment', input.nonInferable.deployment],
    ['Pitfalls', input.nonInferable.pitfalls],
  ];

  for (const [title, content] of sections) {
    lines.push(`## ${title}`);
    lines.push('');
    lines.push(content ?? `<!-- FILL IN: ${title.toLowerCase()} details that agents wouldn't infer from code -->`);
    lines.push('');
  }

  return lines.join('\n');
}

// ============================================================================
// ai.txt (eksperymentalne, niska adopcja, generujemy bo wolne 2 KB ROI)
// ============================================================================

export interface AiTxtInput {
  siteUrl: string;
  /** Polityka użycia: allow training / disallow training / require attribution */
  policy: 'allow' | 'disallow' | 'require_attribution';
  contact?: string;
}

export function generateAiTxt(input: AiTxtInput): string {
  const lines: string[] = [];
  lines.push(`# ai.txt — AI usage policy`);
  lines.push(`# Site: ${input.siteUrl}`);
  lines.push('');
  lines.push(`Policy: ${input.policy}`);
  if (input.contact) lines.push(`Contact: ${input.contact}`);
  lines.push('');
  lines.push('# This file is experimental and not widely adopted as of 2026.');
  lines.push('# Use robots.txt + Content-Signal headers as primary controls.');
  return lines.join('\n');
}
